# default golangci-linter configuration, please reference https://golangci-lint.run/usage/configuration/ for details
run:
  tests: false
output:
  sort-results: true
  format: html
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gofumpt
    - goconst
    - revive
